networks:
  dockers_lan:
    external: true

services:
  uptimekuma:
    image: louislam/uptime-kuma:1
    container_name: uptimekuma
    volumes:
      - './uptimekuma/data:/app/data'
    restart: always
    ports:
      - "3001:3001"
    networks:
      dockers_lan:
        ipv4_address: 192.168.1.52

# docker run -d 
# --restart=always -p 127.0.0.1:3001:3001 -v uptime-kuma:/app/data 
# --name uptime-kuma louislam/uptime-kuma:1