---
- name: setup Linode lab
  hosts: webservers
  become: true
  become_method: ansible.builtin.sudo
  gather_facts: true
  vars_files:
    - vars.yml
  # pre_tasks:
  #   - name: All data disks
  #     ansible.builtin.set_fact:
  #       all_data_disks: "{{ data_disks + office_disks }}"
  #     tags: manage_disks

  roles:
    - role: manage_linux
      tags:
        - manage_linux
        - base_setup

    - role: geerlingguy.docker
      tags:
        - docker
        - base_setup
        - scrutiny

    - role: dockers
      tags: dockers

    - role: manage_zsh
      when: manage_zsh | default(false) | bool
      tags:
        - manage_zsh
        - base_setup
    # - role: validate_parity_config
    #   tags:
    #     - validate
    #     - parity
    #     - config

    # - role: wipecheck
    #   tags: wipecheck



    # - role: stefangweichinger.ansible_rclone
    #   when: install_rclone
    #   tags:
    #     - rclone
    #     - base_setup



#     - role: install_mergerfs
#       tags:
#         - install_mergerfs
#         - mergerfs

#     - role: install_snapraid
#       tags:
#         - install_snapraid
#         - snapraid

#     - role: install_btrfs
#       tags:
#         - install_btrfs
#         - btrfs

#     - role: manage_disks_nas
#       tags:
#         - manage_disks
#         - btrfs

#     - role: configure_mergerfs
#       tags:
#         - configure_mergerfs
#         - mergerfs

#     - role: configure_snapraid
#       tags:
#         - configure_snapraid
#         - snapraid

#     - role: vladgh.samba.server
#       tags: samba

# #    - role: cache_mover
# #      tags: cache_mover

#     - role: docker_scrutiny
#       when: configure_scrutiny
#       tags:
#         - scrutiny
#         - docker

#     - role: configure_hdidle
#       when: configure_hdidle
#       tags: hdidle

#     - role: dockers
#       tags: dockers

#   post_tasks:
#     - name: Display SnapRAID Configuration Notices
#       ansible.builtin.debug:
#         msg: "{{ snapraid_warning_message }}"
#       when: snapraid_warning_message is defined
#       tags:
#         - configure_snapraid
#         - snapraid

#     - name: Display Mount Cleanup Notices
#       ansible.builtin.debug:
#         msg: "{{ mount_cleanup_message }}"
#       when: mount_cleanup_message is defined
#       tags:
#         - manage_disks
#         - btrfs
