[project]
name = "herbylab-nas"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ansible>=11.3.0",
    "ansible-core>=2.18.3",
    "ansible-lint>=25.1.3",
    "github3-py>=4.0.1",
    "pip>=25.0.1",
]
