networks:
  dockers_lan:
    external: true

services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: uid:gid
    network_mode: 'host'
    volumes:
      - './jellyfin/config:/config'
      - './jellyfin/cache:/cache'
      - type: bind
        source: /mnt/media
        target: /media
      - type: bind
        source: /mnt/media2
        target: /media2
        read_only: true
      # # Optional - extra fonts to be used during transcoding with subtitle burn-in
      # - type: bind
      #   source: /path/to/fonts
      #   target: /usr/local/share/fonts/custom
      #   read_only: true
    restart: always
    environment:
      - JELLYFIN_PublishedServerUrl=http://jellyfin.herbylab.lan
    networks:
      dockers_lan:
        ipv4_address: 192.168.1.52

# docker run -d \
#  --name jellyfin \
#  --user uid:gid \
#  --net=host \
#  --volume /path/to/config:/config \ # Alternatively --volume jellyfin-config:/config
#  --volume /path/to/cache:/cache \ # Alternatively --volume jellyfin-cache:/cache
#  --mount type=bind,source=/path/to/media,target=/media \
#  --restart=unless-stopped \
#  jellyfin/jellyfin