---
- name: scrutiny_deploy | Copy scrutiny config file
  ansible.builtin.template:
    src: "./files/scrutiny/compose.j2"
    dest: "{{ dockers_path }}/scrutiny/compose.yml"
    owner: "{{  user }}"
    group: root
    mode: '0644'

- name: scrutiny_deploy | Create and start scrutiny
  community.docker.dockers_compose_v2:
    project_src: "{{dockers_path}}/scrutiny/"
  register: output

- name: scrutiny_deploy | Display warning about privileged mode
  ansible.builtin.debug:
    msg: >
      WARNING: Scrutiny is running in privileged mode, which gives it full access to the host system.
      Disable auto deployment and do this manually yourself if this is an issue for you.
